"""done field in Event

Revision ID: 175da59bf3d8
Revises: 5ff70e3d01ea
Create Date: 2021-07-17 20:47:21.065701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175da59bf3d8'
down_revision = '5ff70e3d01ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'done')
    # ### end Alembic commands ###
