"""colour attribute to Event

Revision ID: 5ff70e3d01ea
Revises: f76976b6027a
Create Date: 2021-06-22 23:50:09.305283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff70e3d01ea'
down_revision = 'f76976b6027a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('color', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'color')
    # ### end Alembic commands ###
